services:
  - type: web
    name: graphone-api
    env: node
    region: oregon
    plan: free

    buildCommand: npm install
    startCommand: node server.js

    envVars:
      - key: NODE_ENV
        value: production

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_ANON_KEY
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: API_KEY
        sync: false

      - key: CORS_ORIGIN
        value: "*"